"""smth

Revision ID: bcf340ec738b
Revises: 50e67960a661
Create Date: 2020-12-10 11:53:57.818708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf340ec738b'
down_revision = '50e67960a661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hall_places', table_name='hall')
    op.drop_table('hall')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hall',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('places', sa.INTEGER(), nullable=True),
    sa.Column('session', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hall_places', 'hall', ['places'], unique=1)
    # ### end Alembic commands ###
