"""genreid

Revision ID: cd9f5b8c8d2e
Revises: 0c99fec02d2a
Create Date: 2020-11-30 13:33:03.077125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9f5b8c8d2e'
down_revision = '0c99fec02d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('genre_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'film', 'genre', ['genre_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'film', type_='foreignkey')
    op.drop_column('film', 'genre_id')
    # ### end Alembic commands ###
